Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/BlockLength:
  Exclude:
    - 'sicily.gemspec'
    - "**/*_spec.rb"
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
Metrics/MethodLength:
  Max: 5
Metrics/ParameterLists:
  Max: 4
Style/GlobalVars:
  AllowedVariables: ['$SICILY_LOG_TO_FILE', '$SICILY_LOAD_USER_CONFIGS']
Lint/RescueException:
  Exclude:
    - 'lib/sicily/batch_processor.rb'